-- ============================================================
-- PLACIFY CHATBOT — FULL DATASET FOR ALL 45 COURSES
-- Import via phpMyAdmin or: mysql -u root -p placify < dataset.sql
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================
-- TABLE STRUCTURES
-- ============================================================

CREATE TABLE IF NOT EXISTS `courses` (
  `course_id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_name` VARCHAR(100) NOT NULL,
  `short_name` VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gd_topics` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `topic` TEXT NOT NULL,
  `stream` VARCHAR(20) DEFAULT NULL,
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hr_questions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `question` TEXT NOT NULL,
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `technical_questions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `question` TEXT NOT NULL,
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `aptitude_questions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `topic` VARCHAR(100),
  `question` TEXT NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mock_interview_questions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `question` TEXT NOT NULL,
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `skills` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `skill_name` VARCHAR(100) NOT NULL,
  `skill_type` VARCHAR(50) DEFAULT 'Technical',
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `coding_problems` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `problem` TEXT NOT NULL,
  `difficulty` VARCHAR(20) DEFAULT 'Easy',
  `hint` TEXT,
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `coding_topics` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `topic` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ats_keywords` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `course_id` INT NOT NULL,
  `keyword` VARCHAR(100) NOT NULL,
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `companies` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_name` VARCHAR(100) NOT NULL,
  `role` VARCHAR(100),
  `salary` VARCHAR(50),
  `type` VARCHAR(50),
  `stream` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `resume_tips` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tip` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- COURSES (45 courses)
-- ============================================================
TRUNCATE TABLE `courses`;
INSERT INTO `courses` (`course_id`, `course_name`, `short_name`) VALUES
(1,  'Computer Science',                    'CS'),
(2,  'Bachelor of Computer Applications',   'BCA'),
(3,  'Master of Computer Applications',     'MCA'),
(4,  'M.Sc Computer Science',               'MSC CS'),
(5,  'Cognitive Science',                   'COGNITIVE'),
(6,  'Data Science',                        'DS'),
(7,  'Artificial Intelligence',             'AI'),
(8,  'Data Science and Artificial Intelligence','DSAI'),
(9,  'Cloud Computing',                     'CLOUD'),
(10, 'Cyber Security',                      'CYBER'),
(11, 'Mathematics',                         'MATHS'),
(12, 'Physics',                             'PHYSICS'),
(13, 'Chemistry',                           'CHEM'),
(14, 'Psychology',                          'PSY'),
(15, 'Clinical Nutrition and Dietetics',    'CND'),
(16, 'Nutrition and Food Service Management','NFSM'),
(17, 'Environmental Science',               'EVS'),
(18, 'Bachelor of Commerce',                'BCOM'),
(19, 'Corporate Secretaryship',             'CORP'),
(20, 'Accounting and Finance',              'AF'),
(21, 'B.Com Honours',                       'HONS'),
(22, 'Business Information Management',     'BIM'),
(23, 'B.Com Computer Applications',         'BCOM CA'),
(24, 'Public Administration',               'PA'),
(25, 'Information Systems Management',      'ISM'),
(26, 'Financial Technology',                'FINTECH'),
(27, 'International Business',              'IB'),
(28, 'Banking and Finance',                 'BF'),
(29, 'Master of Commerce',                  'MCOM'),
(30, 'Bachelor of Business Administration', 'BBA'),
(31, 'Digital Marketing',                   'DM'),
(32, 'Fashion Design',                      'FASHION'),
(33, 'Airport Management',                  'AIRPORT'),
(34, 'English Literature',                  'ENG'),
(35, 'History',                             'HISTORY'),
(36, 'Economics',                           'ECO'),
(37, 'Tamil Literature',                    'TAMIL'),
(38, 'Hindi',                               'HINDI'),
(39, 'Sanskrit',                            'SANSKRIT'),
(40, 'French',                              'FRENCH'),
(41, 'Tourism and Travel Management',       'TOURISM'),
(42, 'M.A English',                         'MA ENG'),
(43, 'M.A Tamil',                           'MA TAMIL'),
(44, 'Visual Communication',                'VISCOM'),
(45, 'Sociology',                           'SOC');

-- ============================================================
-- GD TOPICS
-- ============================================================
TRUNCATE TABLE `gd_topics`;
INSERT INTO `gd_topics` (`course_id`, `topic`, `stream`) VALUES
-- CS (1)
(1,'Is Artificial Intelligence replacing software engineers?','science'),
(1,'Open source vs proprietary software: which is better?','science'),
(1,'Should coding be made mandatory in school curriculum?','science'),
(1,'Cloud computing: the future of data storage','science'),
(1,'Cybersecurity threats in the digital age','science'),
(1,'Can machines ever be truly creative?','science'),
-- BCA (2)
(2,'Is a BCA degree enough to get a software job today?','science'),
(2,'Mobile apps vs web apps: which has a better future?','science'),
(2,'The impact of social media on society','science'),
(2,'Are certifications more valuable than degrees in IT?','science'),
(2,'Work from home vs office — which is better for developers?','science'),
(2,'Gaming industry: career opportunities for tech graduates','science'),
-- MCA (3)
(3,'Should MCA graduates focus on specialization or generalization?','science'),
(3,'Big Data: opportunity or threat to privacy?','science'),
(3,'Is a master''s degree necessary for a software career?','science'),
(3,'Agile vs Waterfall methodology: which is more effective?','science'),
(3,'The role of IoT in transforming smart cities','science'),
(3,'Remote work: boon or bane for the IT industry?','science'),
-- MSC CS (4)
(4,'Research vs industry: which path should CS graduates choose?','science'),
(4,'Quantum computing: will it replace classical computers?','science'),
(4,'Is academic research in CS outdated by the time it is published?','science'),
(4,'Machine learning: hype or the future?','science'),
(4,'Should universities teach more practical skills over theory?','science'),
-- DS (6)
(6,'Data privacy: whose responsibility is it?','science'),
(6,'Is data science a bubble that will burst?','science'),
(6,'Can data predict human behavior accurately?','science'),
(6,'Ethical concerns in AI and data-driven decision making','science'),
(6,'Should data scientists know programming deeply?','science'),
(6,'The role of data science in healthcare transformation','science'),
-- AI (7)
(7,'Will AI cause mass unemployment in the next decade?','science'),
(7,'Autonomous vehicles: are we ready for self-driving cars?','science'),
(7,'AI in healthcare: should machines make medical decisions?','science'),
(7,'Deepfakes and misinformation: is AI a threat to democracy?','science'),
(7,'Should AI development be regulated by governments?','science'),
-- CLOUD (9)
(9,'Is cloud computing making on-premise servers obsolete?','science'),
(9,'Data sovereignty: who owns your cloud data?','science'),
(9,'Multi-cloud vs single cloud strategy for enterprises','science'),
(9,'Cloud gaming: the future of the gaming industry','science'),
(9,'Security risks in cloud adoption for businesses','science'),
-- CYBER (10)
(10,'Is ethical hacking a legitimate career?','science'),
(10,'Ransomware attacks: are companies doing enough to protect data?','science'),
(10,'Should governments have backdoors in encryption?','science'),
(10,'Social engineering: the biggest cybersecurity threat','science'),
(10,'Privacy vs security: finding the right balance','science'),
-- MATHS (11)
(11,'Is mathematics the language of the universe?','science'),
(11,'Pure mathematics vs applied mathematics: which is more valuable?','science'),
(11,'Can mathematics solve all real-world problems?','science'),
(11,'The role of statistics in modern decision making','science'),
(11,'Should advanced mathematics be a mandatory subject in college?','science'),
-- PHYSICS (12)
(12,'Nuclear energy: the solution to global energy crisis?','science'),
(12,'Space exploration: investment or waste of resources?','science'),
(12,'Is renewable energy ready to replace fossil fuels?','science'),
(12,'Quantum mechanics: practical applications vs theoretical value','science'),
(12,'Should India invest more in scientific research?','science'),
-- CHEM (13)
(13,'Chemical industry: innovation vs environmental responsibility','science'),
(13,'Are synthetic foods safe for long-term consumption?','science'),
(13,'The role of chemistry in combating climate change','science'),
(13,'Plastic pollution: can chemical solutions solve it?','science'),
(13,'Pharmaceutical industry: profit vs public health','science'),
-- PSY (14)
(14,'Is social media causing a mental health crisis?','science'),
(14,'Should therapy be accessible and free for everyone?','science'),
(14,'Nature vs nurture: what shapes human personality?','science'),
(14,'The stigma around mental health in India','science'),
(14,'Can AI replace psychologists and therapists?','science'),
-- CND (15)
(15,'Is India ready for a nutrition revolution?','science'),
(15,'Processed food vs home-cooked meals: long-term health impact','science'),
(15,'Should nutritionists be given more authority in hospitals?','science'),
(15,'Obesity epidemic: lifestyle disease or genetic predisposition?','science'),
(15,'The role of diet in preventing lifestyle diseases','science'),
-- NFSM (16)
(16,'Food safety regulations in India: are they sufficient?','science'),
(16,'The rise of veganism: trend or sustainable lifestyle?','science'),
(16,'Organic farming vs conventional farming: which is better?','science'),
(16,'Hotel and food service industry post-COVID recovery','science'),
(16,'Should food labeling be made more transparent in India?','science'),
-- EVS (17)
(17,'Climate change: whose responsibility is it?','science'),
(17,'Should single-use plastics be completely banned?','science'),
(17,'Urbanization: threat to biodiversity?','science'),
(17,'Green economy: opportunity or challenge for India?','science'),
(17,'Can technology solve environmental problems?','science'),
-- BCOM (18)
(18,'GST: has it simplified or complicated Indian taxation?','commerce'),
(18,'E-commerce: threat or opportunity for traditional retail?','commerce'),
(18,'Cryptocurrency: should India legalize it?','commerce'),
(18,'Financial literacy: why is it lacking in India?','commerce'),
(18,'Corporate social responsibility: obligation or opportunity?','commerce'),
-- CORP (19)
(19,'Corporate governance: are Indian companies truly compliant?','commerce'),
(19,'Role of company secretaries in modern business','commerce'),
(19,'Mergers and acquisitions: beneficial for employees?','commerce'),
(19,'Insider trading: how can it be effectively prevented?','commerce'),
(19,'Startup culture vs traditional corporate culture','commerce'),
-- AF (20)
(20,'Should the Indian rupee become a global reserve currency?','commerce'),
(20,'Impact of inflation on middle-class savings','commerce'),
(20,'Is FDI always beneficial for developing countries?','commerce'),
(20,'The role of chartered accountants in fraud prevention','commerce'),
(20,'Budget 2025: does it address common man needs?','commerce'),
-- BBA (30)
(30,'Leadership: born or made?','commerce'),
(30,'Start-up ecosystem in India: challenges and opportunities','commerce'),
(30,'Social media marketing: replacing traditional advertising?','commerce'),
(30,'Is an MBA necessary after BBA?','commerce'),
(30,'Women in leadership: breaking the glass ceiling','commerce'),
(30,'Gig economy: future of work or exploitation of workers?','commerce'),
-- FINTECH (26)
(26,'UPI and digital payments: transforming India''s economy','commerce'),
(26,'Will cryptocurrency replace traditional banking?','commerce'),
(26,'Fintech startups: disrupting or complementing traditional banks?','commerce'),
(26,'BNPL (Buy Now Pay Later): financial freedom or debt trap?','commerce'),
(26,'The role of AI in personal finance management','commerce'),
-- IB (27)
(27,'Is globalization good for developing nations?','commerce'),
(27,'Trade wars: impact on emerging economies','commerce'),
(27,'Should India focus more on exports or domestic consumption?','commerce'),
(27,'WTO and its relevance for India in 2025','commerce'),
(27,'Currency devaluation: strategy or desperation?','commerce'),
-- DM (31)
(31,'Is influencer marketing more effective than traditional ads?','commerce'),
(31,'Data privacy vs personalized advertising: where to draw the line?','commerce'),
(31,'Short-form content: the future of digital marketing?','commerce'),
(31,'Can small businesses compete with big brands online?','commerce'),
(31,'AI in content creation: threat or tool for marketers?','commerce'),
-- FASHION (32)
(32,'Fast fashion: a threat to the environment?','commerce'),
(32,'Sustainable fashion: trend or the future of the industry?','commerce'),
(32,'Can Indian fashion compete globally?','commerce'),
(32,'Social media and its impact on fashion trends','commerce'),
(32,'Should fashion schools teach more business skills?','commerce'),
-- AIRPORT (33)
(33,'Is India''s aviation sector ready for rapid expansion?','commerce'),
(33,'Privatization of airports: pros and cons','commerce'),
(33,'Drone delivery: future of cargo logistics?','commerce'),
(33,'Air travel affordability: luxury or a basic right?','commerce'),
(33,'The impact of COVID-19 on the global aviation industry','commerce'),
-- TAMIL (37)
(37,'Tamil language: preserving classical roots in the modern era','arts'),
(37,'Should Tamil be made compulsory in Tamil Nadu schools?','arts'),
(37,'Classical languages and their relevance in today''s job market','arts'),
(37,'Digital preservation of Tamil literature and heritage','arts'),
(37,'The global recognition of Tamil as a language','arts'),
-- ENG (34)
(34,'Is English literature still relevant in the digital age?','arts'),
(34,'Should regional languages replace English in education?','arts'),
(34,'The power of storytelling in shaping society','arts'),
(34,'Social media and the decline of formal writing skills','arts'),
(34,'Can literature create social change?','arts'),
-- HISTORY (35)
(35,'Should colonial history be taught critically in schools?','arts'),
(35,'Preservation of historical monuments: whose responsibility?','arts'),
(35,'Can we learn from history to avoid future conflicts?','arts'),
(35,'The role of historians in shaping national identity','arts'),
(35,'Digital archives: revolutionizing historical research','arts'),
-- ECO (36)
(36,'Universal Basic Income: solution to poverty or economic disaster?','arts'),
(36,'Is India''s GDP growth benefiting the common man?','arts'),
(36,'Green economy: balancing growth and sustainability','arts'),
(36,'Informal economy: challenge or strength for India?','arts'),
(36,'Privatization of public sector banks: good or bad?','arts'),
-- HINDI (38)
(38,'Should Hindi be declared the official language of India?','arts'),
(38,'The influence of English on Hindi language and culture','arts'),
(38,'Bollywood: a catalyst for Hindi language spread globally?','arts'),
(38,'Hindi literature in the digital age','arts'),
(38,'Is Hindi becoming a symbol of cultural dominance?','arts'),
-- TOURISM (41)
(41,'Is sustainable tourism possible in India?','arts'),
(41,'Over-tourism: destroying the places we love to visit?','arts'),
(41,'Should India invest more in heritage tourism?','arts'),
(41,'The impact of social media on travel trends','arts'),
(41,'Medical tourism: India as a global destination','arts'),
-- VISCOM (44)
(44,'Is digital media making print media obsolete?','arts'),
(44,'Ethical boundaries in photojournalism','arts'),
(44,'The role of visual communication in social change','arts'),
(44,'OTT platforms vs traditional cinema: who wins?','arts'),
(44,'Can design thinking solve real-world problems?','arts'),
-- SOC (45)
(45,'Casteism in modern India: progress or persistent problem?','arts'),
(45,'Social media: tool for social change or echo chamber?','arts'),
(45,'Feminism in India: aspirations vs ground reality','arts'),
(45,'Urbanization and its impact on Indian joint families','arts'),
(45,'Child labor: despite laws, why does it persist?','arts');

-- ============================================================
-- HR QUESTIONS
-- ============================================================
TRUNCATE TABLE `hr_questions`;
INSERT INTO `hr_questions` (`course_id`, `question`) VALUES
-- Science courses (1-17) — technical flavor
(1,'Tell me about yourself and your CS background.'),
(1,'Why did you choose Computer Science as your major?'),
(1,'What is your biggest technical achievement?'),
(1,'How do you keep yourself updated with new technologies?'),
(1,'Describe a challenging project and how you handled it.'),
(2,'Tell me about yourself and your BCA journey.'),
(2,'Why should we hire a BCA fresher for this role?'),
(2,'What programming languages are you comfortable with?'),
(2,'Describe a project you built during your BCA.'),
(2,'How do you handle pressure during deadlines?'),
(3,'Walk me through your MCA specialization and projects.'),
(3,'Why did you pursue MCA after graduation?'),
(3,'What is your approach to learning a new technology?'),
(3,'How do you handle conflicts in a team project?'),
(3,'Where do you see yourself in 5 years?'),
(4,'Why did you choose M.Sc Computer Science?'),
(4,'How does your research background help in industry?'),
(4,'What are your strengths as a CS postgraduate?'),
(4,'Tell me about a time you solved a complex problem.'),
(4,'How do you balance theory and practical application?'),
(5,'What interests you about Cognitive Science?'),
(5,'How does your background help in AI or UX roles?'),
(5,'Describe a situation where you applied critical thinking.'),
(5,'What are your key strengths as a Cognitive Science student?'),
(5,'Why should we hire you for a data or research role?'),
(6,'Why are you passionate about Data Science?'),
(6,'What tools and libraries have you used for data analysis?'),
(6,'Describe a data project you have worked on.'),
(6,'How do you handle missing or inconsistent data?'),
(6,'What is your approach to communicating data insights?'),
(7,'Why did you choose Artificial Intelligence?'),
(7,'What AI frameworks or tools have you worked with?'),
(7,'Describe an AI project you have built or contributed to.'),
(7,'How do you handle model overfitting?'),
(7,'What are the ethical challenges of AI in your view?'),
(8,'How is DSAI different from standalone DS or AI?'),
(8,'What datasets have you worked with in your projects?'),
(8,'Describe a situation where data helped you make a decision.'),
(8,'What ML algorithms are you most comfortable with?'),
(8,'How do you stay current in the field of AI and data science?'),
(9,'Why is Cloud Computing important for businesses today?'),
(9,'What cloud platforms have you worked with?'),
(9,'Describe a cloud architecture you have designed or studied.'),
(9,'How do you ensure security in cloud deployments?'),
(9,'What are the advantages of serverless computing?'),
(10,'Why did you choose Cyber Security?'),
(10,'What cybersecurity tools are you familiar with?'),
(10,'Describe a real-world cyber attack and how it could be prevented.'),
(10,'What is your approach to ethical hacking?'),
(10,'How do you handle a situation where you discover a system vulnerability?'),
(11,'Why did you choose Mathematics as your major?'),
(11,'How does mathematics apply to your target career?'),
(11,'Describe a complex mathematical problem you solved.'),
(11,'What are your strengths in analytical thinking?'),
(11,'How do you explain complex concepts to non-technical people?'),
(12,'Why did you choose Physics?'),
(12,'How does your Physics background help in technology roles?'),
(12,'Describe a research or lab project you are proud of.'),
(12,'What are your strongest analytical skills?'),
(12,'How do you handle failure in experiments or research?'),
(13,'Why did you choose Chemistry?'),
(13,'What lab skills do you bring to this role?'),
(13,'How does your Chemistry background apply in industry?'),
(13,'Tell me about a lab experiment or project you led.'),
(13,'How do you handle safety protocols in a lab environment?'),
(14,'Why did you choose Psychology?'),
(14,'How does understanding human behavior help in corporate roles?'),
(14,'Describe a situation where you resolved a conflict.'),
(14,'What are your strengths in communication and empathy?'),
(14,'Where do you see a psychologist fitting in a corporate team?'),
(15,'Why did you choose Clinical Nutrition and Dietetics?'),
(15,'How do you counsel a patient with dietary restrictions?'),
(15,'Tell me about a nutritional plan you designed.'),
(15,'How do you stay updated with nutritional science research?'),
(15,'What are the biggest challenges in promoting healthy eating?'),
(16,'Why did you choose Nutrition and Food Service Management?'),
(16,'How do you ensure food safety standards in a service setting?'),
(16,'Tell me about a food service or catering project you managed.'),
(16,'How do you handle customer complaints in food service?'),
(16,'What skills do you bring to a food industry role?'),
(17,'Why did you choose Environmental Science?'),
(17,'How can industries become more environmentally responsible?'),
(17,'Describe a research project you did on environmental issues.'),
(17,'What are your strengths in environmental analysis?'),
(17,'How do you handle working in fieldwork conditions?'),
-- Commerce (18-33)
(18,'Tell me about yourself and your commerce background.'),
(18,'Why did you choose B.Com?'),
(18,'What accounting or finance tools are you familiar with?'),
(18,'How do you handle numerical pressure and deadlines?'),
(18,'Where do you see yourself in the finance sector in 5 years?'),
(19,'Why did you choose Corporate Secretaryship?'),
(19,'What do you know about company law and compliance?'),
(19,'How do you stay updated on regulatory changes?'),
(19,'Tell me about a case study in corporate governance you studied.'),
(19,'What are your strengths for a compliance or legal support role?'),
(20,'Why did you choose Accounting and Finance?'),
(20,'What is your experience with financial statements and analysis?'),
(20,'Describe a financial project or case study you worked on.'),
(20,'How do you handle errors in financial reports?'),
(20,'What are your long-term goals in the finance industry?'),
(21,'Why did you choose B.Com Honours?'),
(21,'What differentiates you from a regular B.Com graduate?'),
(21,'Describe your strongest academic achievement.'),
(21,'How do you apply accounting concepts in real-world scenarios?'),
(21,'What additional certifications have you pursued?'),
(22,'Why did you choose Business Information Management?'),
(22,'How does BIM bridge the gap between business and technology?'),
(22,'What ERP or business software are you familiar with?'),
(22,'Describe a business process improvement project you worked on.'),
(22,'What are your career goals in business management?'),
(23,'How does a B.Com CA graduate differ from a regular B.Com?'),
(23,'What accounting software tools have you learned?'),
(23,'Describe how technology is changing the accounting profession.'),
(23,'Why should we hire you for a finance-tech role?'),
(23,'What are your strengths in both accounting and IT?'),
(24,'Why did you choose Public Administration?'),
(24,'How do you see yourself contributing to public sector roles?'),
(24,'What are the biggest challenges in Indian public administration?'),
(24,'Describe a case study in public policy you found interesting.'),
(24,'What are your strengths for government or NGO work?'),
(25,'Why did you choose Information Systems Management?'),
(25,'How does ISM differ from a pure IT or pure business degree?'),
(25,'Describe a business information system project you worked on.'),
(25,'How do you ensure data security in business systems?'),
(25,'Where do you see yourself in information management in 5 years?'),
(26,'Why did you choose Financial Technology?'),
(26,'What do you understand about digital payment systems?'),
(26,'How is blockchain changing the financial industry?'),
(26,'Describe a fintech product or innovation you admire.'),
(26,'What programming or data skills do you bring to fintech?'),
(27,'Why did you choose International Business?'),
(27,'What do you understand about global trade regulations?'),
(27,'Describe a situation where you worked in a cross-cultural team.'),
(27,'What languages or global market knowledge do you have?'),
(27,'How do you see India''s role in global trade growing?'),
(28,'Why did you choose Banking and Finance?'),
(28,'What do you understand about current RBI policies?'),
(28,'How would you handle a customer complaint in a bank?'),
(28,'Describe your understanding of KYC and AML procedures.'),
(28,'What are your strengths for a banking career?'),
(29,'Why did you choose M.Com?'),
(29,'How does your postgraduate background add value to industry?'),
(29,'Describe your thesis or major research project.'),
(29,'What are advanced accounting or finance concepts you are comfortable with?'),
(29,'Where do you see yourself in academia vs industry?'),
(30,'Tell me about yourself and your BBA background.'),
(30,'Why did you choose BBA?'),
(30,'What leadership roles have you held?'),
(30,'Describe a time you led a team to achieve a goal.'),
(30,'What is your management style?'),
(31,'Why did you choose Digital Marketing?'),
(31,'What digital marketing tools are you proficient in?'),
(31,'Describe a campaign you ran or analyzed.'),
(31,'How do you measure ROI on a digital marketing campaign?'),
(31,'How do you keep up with changing social media algorithms?'),
(32,'Why did you choose Fashion Design?'),
(32,'How do you balance creativity with commercial requirements?'),
(32,'Describe a fashion project or collection you designed.'),
(32,'How do you handle feedback on your designs?'),
(32,'Where do you see yourself in the fashion industry in 5 years?'),
(33,'Why did you choose Airport Management?'),
(33,'How do you handle high-pressure situations in operations?'),
(33,'What do you know about airport safety and security protocols?'),
(33,'Describe your customer service skills.'),
(33,'How would you handle a flight delay situation with passengers?'),
-- Arts (34-45)
(34,'Tell me about yourself and your English Literature background.'),
(34,'How does literature help in corporate communication roles?'),
(34,'What are your strongest writing or communication skills?'),
(34,'Describe a piece of writing you are proud of.'),
(34,'Why should we hire an English Literature graduate?'),
(35,'Why did you choose History?'),
(35,'How does historical analysis apply in research or government roles?'),
(35,'Describe a historical event that shaped modern society.'),
(35,'What are your strongest research and analytical skills?'),
(35,'How do you present complex historical information clearly?'),
(36,'Why did you choose Economics?'),
(36,'How do you apply economic theories to real-world situations?'),
(36,'Describe an economic issue in India you feel strongly about.'),
(36,'What quantitative skills do you bring to this role?'),
(36,'Where do you see yourself in the economics field in 5 years?'),
(37,'Tell me about yourself and your Tamil Literature background.'),
(37,'How does knowledge of Tamil literature help in communication roles?'),
(37,'What are your strengths in Tamil and multilingual communication?'),
(37,'Describe your experience in content writing or translation work.'),
(37,'Why should we hire a Tamil Literature graduate?'),
(38,'Why did you choose Hindi as your major?'),
(38,'How do you use your language skills professionally?'),
(38,'Describe a translation or content project you worked on.'),
(38,'What roles are you targeting with a Hindi background?'),
(38,'How do you handle working in multilingual environments?'),
(39,'Why did you choose Sanskrit?'),
(39,'How does Sanskrit scholarship help in research or academic roles?'),
(39,'What is the relevance of Sanskrit in modern India?'),
(39,'Describe a research project you completed in Sanskrit studies.'),
(39,'What career path are you targeting?'),
(40,'Why did you choose French?'),
(40,'What level of French language proficiency have you achieved?'),
(40,'How does French language knowledge open career opportunities?'),
(40,'Describe a translation or language project you worked on.'),
(40,'What industries do you target with a French language skill?'),
(41,'Why did you choose Tourism and Travel Management?'),
(41,'How do you handle demanding or difficult tourists?'),
(41,'Describe a tour or travel plan you designed.'),
(41,'What customer service skills do you bring?'),
(41,'How do you see Indian tourism growing in the next decade?'),
(42,'Why did you choose M.A English?'),
(42,'How does your postgraduate English degree prepare you for industry?'),
(42,'Describe your research or dissertation topic.'),
(42,'What content or communication roles are you targeting?'),
(42,'How do you handle writing under tight deadlines?'),
(43,'Why did you choose M.A Tamil?'),
(43,'What research or academic projects have you completed?'),
(43,'How do you apply Tamil studies in modern content roles?'),
(43,'What career path are you planning?'),
(43,'How do you bridge traditional Tamil studies with digital media?'),
(44,'Why did you choose Visual Communication?'),
(44,'What design tools and software are you proficient in?'),
(44,'Describe a visual design project you are proud of.'),
(44,'How do you handle creative differences with a client?'),
(44,'What is your design process from concept to delivery?'),
(45,'Why did you choose Sociology?'),
(45,'How does sociology help in HR, NGO, or policy roles?'),
(45,'Describe a social issue you researched in depth.'),
(45,'What are your strengths in fieldwork and community research?'),
(45,'Where do you see a sociology graduate fitting in corporate India?');

-- ============================================================
-- TECHNICAL QUESTIONS
-- ============================================================
TRUNCATE TABLE `technical_questions`;
INSERT INTO `technical_questions` (`course_id`, `question`) VALUES
(1,'Explain the difference between process and thread.'),
(1,'What is normalization in databases? Explain 1NF, 2NF, 3NF.'),
(1,'What is the time complexity of binary search?'),
(1,'Explain TCP vs UDP — when would you use each?'),
(1,'What is a deadlock in OS and how is it prevented?'),
(2,'What is the difference between OOP and procedural programming?'),
(2,'Explain the four pillars of Object-Oriented Programming.'),
(2,'What is a primary key and foreign key in SQL?'),
(2,'What is the difference between GET and POST in HTTP?'),
(2,'Explain inheritance with a simple example in Java or Python.'),
(3,'What is a design pattern? Explain Singleton with an example.'),
(3,'Explain the MVC architecture pattern.'),
(3,'What is a RESTful API? How does it differ from SOAP?'),
(3,'What is indexing in databases and why is it used?'),
(3,'Explain the CAP theorem in distributed systems.'),
(4,'What is the difference between supervised and unsupervised learning?'),
(4,'Explain the concept of overfitting and how to avoid it.'),
(4,'What is Big O notation? Give examples.'),
(4,'Explain what a neural network is.'),
(4,'What is the difference between stack memory and heap memory?'),
(5,'What is machine learning and how does it relate to cognitive science?'),
(5,'Explain natural language processing with a real-world example.'),
(5,'What is cognitive computing and how is it applied in AI?'),
(5,'Explain the concept of human-computer interaction.'),
(5,'What tools do you use for data analysis and visualization?'),
(6,'What is the difference between classification and regression?'),
(6,'Explain how a decision tree works.'),
(6,'What is feature engineering and why is it important?'),
(6,'How do you handle imbalanced datasets?'),
(6,'What is the difference between Pandas and NumPy?'),
(7,'Explain the difference between deep learning and machine learning.'),
(7,'What is a convolutional neural network (CNN)?'),
(7,'How does backpropagation work?'),
(7,'What is transfer learning and when is it useful?'),
(7,'Explain the difference between precision and recall.'),
(8,'What is the end-to-end pipeline of a data science project?'),
(8,'How would you explain a model''s predictions to a non-technical audience?'),
(8,'What is cross-validation and why is it used?'),
(8,'Explain the difference between bagging and boosting.'),
(8,'What is gradient descent?'),
(9,'What is the difference between IaaS, PaaS, and SaaS?'),
(9,'Explain auto-scaling in cloud environments.'),
(9,'What is a containerization? How does Docker work?'),
(9,'Explain Kubernetes and its role in container orchestration.'),
(9,'What are the differences between public, private, and hybrid clouds?'),
(10,'What is the difference between symmetric and asymmetric encryption?'),
(10,'Explain how SQL injection works and how to prevent it.'),
(10,'What is a firewall and how does it work?'),
(10,'Explain the concept of a VPN.'),
(10,'What is the difference between IDS and IPS?'),
(11,'What is the difference between permutation and combination?'),
(11,'Explain what a matrix is and its applications in computing.'),
(11,'What is linear regression in statistics?'),
(11,'Explain Bayes theorem with an example.'),
(11,'What is the difference between discrete and continuous probability distributions?'),
(12,'Explain Newton''s three laws of motion.'),
(12,'What is the difference between speed and velocity?'),
(12,'Explain semiconductor physics in simple terms.'),
(12,'What is quantum entanglement?'),
(12,'How does a laser work?'),
(13,'What is the difference between organic and inorganic chemistry?'),
(13,'Explain Le Chatelier''s principle.'),
(13,'What is chromatography used for?'),
(13,'Explain the concept of pH and its importance.'),
(13,'What is a catalyst and how does it work?'),
(14,'What is cognitive behavioral therapy (CBT)?'),
(14,'Explain Maslow''s hierarchy of needs.'),
(14,'What is the difference between classical and operant conditioning?'),
(14,'Explain what emotional intelligence is and why it matters at work.'),
(14,'What statistical tools are used in psychological research?'),
(15,'What is the difference between macronutrients and micronutrients?'),
(15,'Explain the role of dietary fiber in digestion.'),
(15,'What is BMI and its limitations as a health indicator?'),
(15,'How do you design a diet plan for a diabetic patient?'),
(15,'What is the difference between saturated and unsaturated fats?'),
(16,'What are HACCP principles in food safety?'),
(16,'Explain the difference between food spoilage and food contamination.'),
(16,'What are the key considerations in large-scale food production?'),
(16,'How do you maintain quality control in a food service setting?'),
(16,'What is the significance of food labeling regulations?'),
(17,'What is the carbon cycle and why is it important?'),
(17,'Explain the greenhouse effect.'),
(17,'What is biodiversity and why does it matter?'),
(17,'Explain sustainable development with an example.'),
(17,'What is Environmental Impact Assessment (EIA)?'),
-- Commerce
(18,'What is the difference between trial balance and balance sheet?'),
(18,'Explain the concept of double-entry bookkeeping.'),
(18,'What is GST and how does it affect businesses?'),
(18,'Explain the difference between direct and indirect taxes.'),
(18,'What is the purpose of bank reconciliation?'),
(19,'What is the role of a company secretary?'),
(19,'Explain the key provisions of the Companies Act 2013.'),
(19,'What is a board resolution and when is it required?'),
(19,'Explain the concept of memorandum and articles of association.'),
(19,'What is the significance of annual general meetings?'),
(20,'Explain the difference between cash basis and accrual basis accounting.'),
(20,'What is the time value of money?'),
(20,'How do you calculate working capital?'),
(20,'What is NPV and how is it used in investment decisions?'),
(20,'Explain the difference between equity and debt financing.'),
(21,'What is the difference between gross profit and net profit?'),
(21,'Explain the concept of financial leverage.'),
(21,'What are the key financial ratios used in analysis?'),
(21,'How do you read and interpret a cash flow statement?'),
(21,'What is forensic accounting?'),
(22,'What is an ERP system and why is it used?'),
(22,'Explain the concept of business intelligence.'),
(22,'What is a data warehouse?'),
(22,'How does information management support business decisions?'),
(22,'Explain the concept of supply chain management.'),
(23,'What accounting software tools are you familiar with?'),
(23,'Explain how Tally handles GST entries.'),
(23,'What is the difference between DBMS and RDBMS?'),
(23,'How is Python used in accounting and finance?'),
(23,'What is cloud-based accounting?'),
(24,'What is the difference between centralized and decentralized administration?'),
(24,'Explain the concept of e-governance.'),
(24,'What are the key functions of local government in India?'),
(24,'Explain the concept of public policy making.'),
(24,'What is the RTI Act and its significance?'),
(25,'What is the difference between data and information?'),
(25,'Explain the concept of a management information system (MIS).'),
(25,'What is cybersecurity and why does it matter for businesses?'),
(25,'Explain the difference between structured and unstructured data.'),
(25,'What is cloud computing and how is it used in business?'),
(26,'What is blockchain and how does it apply to finance?'),
(26,'Explain how UPI works technically.'),
(26,'What is algorithmic trading?'),
(26,'How does machine learning apply in credit scoring?'),
(26,'What is RegTech and why is it important?'),
(27,'What is comparative advantage in international trade?'),
(27,'Explain the difference between tariff and non-tariff barriers.'),
(27,'What is a letter of credit in international trade?'),
(27,'Explain foreign exchange risk and how it is managed.'),
(27,'What is the role of the World Trade Organization?'),
(28,'What is the difference between repo rate and reverse repo rate?'),
(28,'Explain KYC and AML procedures in banking.'),
(28,'What is a non-performing asset (NPA)?'),
(28,'Explain the role of SEBI in Indian financial markets.'),
(28,'What is the difference between a savings account and a current account?'),
(29,'Explain the concept of activity-based costing.'),
(29,'What is the difference between fund-based and non-fund-based credit?'),
(29,'Explain how derivatives work in financial markets.'),
(29,'What is the difference between IFRS and GAAP?'),
(29,'Explain portfolio management theory.'),
(30,'What is SWOT analysis? Give an example.'),
(30,'Explain Porter''s five forces model.'),
(30,'What is the difference between leadership and management?'),
(30,'Explain the concept of market segmentation.'),
(30,'What is break-even analysis?'),
(31,'What is SEO and how does it work?'),
(31,'Explain the difference between SEM and SMM.'),
(31,'What is a sales funnel in digital marketing?'),
(31,'How do you analyze Google Analytics data?'),
(31,'What is content marketing and why is it important?'),
(32,'What is the difference between haute couture and ready-to-wear?'),
(32,'Explain the concept of the fashion product life cycle.'),
(32,'What is merchandising in the fashion industry?'),
(32,'How does trend forecasting work?'),
(32,'What software tools do fashion designers use?'),
(33,'What is the ICAO and its role in aviation?'),
(33,'Explain the concept of airport capacity planning.'),
(33,'What is the difference between airside and landside operations?'),
(33,'How is airline revenue management handled?'),
(33,'What are the key safety regulations in airport operations?'),
-- Arts
(34,'What is the difference between prose and poetry?'),
(34,'Explain the concept of literary criticism.'),
(34,'What is the significance of the Romantic movement in literature?'),
(34,'How does literature reflect society?'),
(34,'What is content writing and how does SEO relate to it?'),
(35,'What is the difference between primary and secondary historical sources?'),
(35,'Explain the concept of historiography.'),
(35,'What is the significance of the Indian independence movement?'),
(35,'How do historians verify the authenticity of historical records?'),
(35,'What are the major schools of historical thought?'),
(36,'What is the difference between microeconomics and macroeconomics?'),
(36,'Explain supply and demand with a real example.'),
(36,'What is GDP and how is it measured?'),
(36,'Explain the concept of fiscal policy.'),
(36,'What is opportunity cost?'),
(37,'Explain the significance of Sangam literature.'),
(37,'What are the five classical epics of Tamil literature?'),
(37,'How does Tamil literature contribute to Indian cultural heritage?'),
(37,'What is the relevance of Thirukkural in modern life?'),
(37,'How is digital media changing Tamil content consumption?'),
(38,'Explain the history and development of Hindi literature.'),
(38,'What is Devanagari script and how is it structured?'),
(38,'Who are the major writers of modern Hindi literature?'),
(38,'What is the significance of Premchand in Hindi literature?'),
(38,'How is Hindi used in mass media today?'),
(39,'What is the significance of Sanskrit as a classical language?'),
(39,'Explain the structure of Sanskrit grammar.'),
(39,'What are the major works of Sanskrit literature?'),
(39,'How is Sanskrit connected to modern Indian languages?'),
(39,'What is the relevance of studying Sanskrit today?'),
(40,'Explain the structure of French verb conjugation.'),
(40,'What is the cultural significance of French language globally?'),
(40,'What are the major French literary movements?'),
(40,'How does French language proficiency help in business?'),
(40,'What is the Alliance Française and its role?'),
(41,'What is sustainable tourism?'),
(41,'Explain the concept of ecotourism.'),
(41,'What is the role of a tour operator vs a travel agent?'),
(41,'How do you plan an itinerary for a group tour?'),
(41,'What is MICE tourism?'),
(42,'Explain the concept of postcolonial literature.'),
(42,'What is comparative literature?'),
(42,'Explain the role of language in shaping identity.'),
(42,'What is discourse analysis?'),
(42,'How does M.A English prepare you for content or media roles?'),
(43,'What is the contribution of Subramania Bharati to Tamil literature?'),
(43,'Explain the Akam and Puram traditions in Tamil poetry.'),
(43,'What is the historical significance of the Tamil Sangam period?'),
(43,'How is Tamil literature being preserved in the digital age?'),
(43,'What career opportunities exist for M.A Tamil graduates?'),
(44,'What is the difference between raster and vector graphics?'),
(44,'Explain the role of typography in design.'),
(44,'What is the golden ratio and how is it used in design?'),
(44,'What is the difference between UI and UX design?'),
(44,'What design software are you proficient in?'),
(45,'What is the difference between qualitative and quantitative research in sociology?'),
(45,'Explain the concept of social stratification.'),
(45,'What is the significance of Emile Durkheim in sociology?'),
(45,'Explain the concept of social mobility.'),
(45,'What are the major sociological theories?');

-- ============================================================
-- APTITUDE QUESTIONS
-- ============================================================
TRUNCATE TABLE `aptitude_questions`;
INSERT INTO `aptitude_questions` (`course_id`, `topic`, `question`, `answer`) VALUES
-- Science
(1,'Number Series','What comes next: 2, 4, 8, 16, ?','32'),
(1,'Percentage','A software license costs ₹2000. After a 15% discount, what is the price?','₹1700'),
(1,'Time & Work','A can do a job in 10 days and B in 15 days. Working together, in how many days?','6 days'),
(1,'Logical Reasoning','All programmers are engineers. Some engineers are managers. Can all programmers be managers?','Not necessarily'),
(1,'Data Interpretation','If a server handles 500 requests/sec and traffic doubles, how many requests in 3 seconds?','3000'),
(2,'Percentage','A BCA student scored 420 out of 600. What is the percentage?','70%'),
(2,'Profit & Loss','Bought a laptop for ₹30,000. Sold for ₹36,000. Profit percentage?','20%'),
(2,'Time & Distance','A train travels 360 km in 4 hours. Speed in km/hr?','90 km/hr'),
(2,'Series','1, 3, 7, 15, 31, ?','63'),
(2,'Logical','If A > B and B > C, is A > C?','Yes'),
(3,'Time & Work','3 programmers finish a module in 12 days. How long for 4 programmers?','9 days'),
(3,'Percentage','Server uptime is 98.5%. Downtime in hours per year (8760 hrs)?','131.4 hours'),
(3,'Ratio','Male to female ratio in class is 3:2. Total 40 students. How many females?','16'),
(3,'Coding Logic','What is the output: x=5; x=x*2+3?','13'),
(3,'Data Interpretation','A database has 1000 rows. 30% are deleted. 10% of remaining are added. Total?','721'),
(6,'Probability','A dataset has 60 correct predictions out of 100. What is accuracy?','60%'),
(6,'Percentage','Training data is 80% of 5000 samples. How many in test set?','1000'),
(6,'Ratio','Feature A contributes 3 times more than Feature B. Total importance is 100. What is A?','75'),
(6,'Data Interpretation','A chart shows sales: Jan-100, Feb-150, Mar-120. What is the average?','123.33'),
(6,'Number Series','10, 20, 40, 80, ?','160'),
(7,'Logical Reasoning','If all AI models are algorithms, and some algorithms are efficient, can all AI models be efficient?','Not necessarily'),
(7,'Percentage','An AI model is 85% accurate on 200 samples. How many correct?','170'),
(7,'Time & Work','Training one model takes 6 hours. Running 4 models in parallel on a cluster - how many hours?','6 hours (parallel)'),
(7,'Data','A neural network has 3 layers: 4, 6, 3 neurons. Total connections between layer 1 and 2?','24'),
(7,'Series','1, 1, 2, 3, 5, 8, ?','13 (Fibonacci)'),
-- Commerce
(18,'Profit & Loss','Cost price of goods: ₹5000. Selling price: ₹6000. Profit percentage?','20%'),
(18,'Simple Interest','Principal ₹10,000, Rate 8%, Time 3 years. Simple Interest?','₹2400'),
(18,'Percentage','Salary increased from ₹20,000 to ₹23,000. Percentage increase?','15%'),
(18,'Ratio','Assets to liabilities ratio is 5:3. Total capital is ₹80,000. Find liabilities.','₹30,000'),
(18,'Time & Work','A bookkeeper processes 200 invoices/day. How many in 5 days with a helper who does 150/day?','1750'),
(30,'Profit & Loss','A product is sold at 25% profit. If cost is ₹800, what is the selling price?','₹1000'),
(30,'Percentage','Market share increased from 20% to 25%. Percentage increase in market share?','25%'),
(30,'Ratio','Investment ratio of two partners is 3:5. Total profit ₹40,000. Find larger share.','₹25,000'),
(30,'Time & Distance','A sales rep travels 150 km in 2.5 hours. What is average speed?','60 km/hr'),
(30,'Data','Monthly sales: ₹50K, ₹60K, ₹55K, ₹70K. What is the average?','₹58,750'),
(26,'Percentage','Transaction fee is 1.5% of ₹10,000. Fee amount?','₹150'),
(26,'Simple Interest','Loan ₹50,000 at 12% per year for 2 years. Total interest?','₹12,000'),
(26,'Data','A UPI app has 50 lakh users. 20% make daily transactions. How many daily?','10 lakh'),
(26,'Ratio','Investment A gives ₹200 on ₹1000. Investment B gives ₹300 on ₹1200. Which has better return?','Investment A (20% vs 25%) — B'),
(26,'Series','100, 105, 115, 130, ?','150'),
-- Arts
(37,'Number Series','5, 10, 20, 40, ?','80'),
(37,'Percentage','A book originally costs ₹400. Discounted at 10%. Final price?','₹360'),
(37,'Time & Work','A writer completes 4 articles in 2 days. How many in 7 days?','14 articles'),
(37,'Logical','If all Tamil scholars are linguists, and Ravi is a Tamil scholar, is Ravi a linguist?','Yes'),
(37,'Ratio','Words in Tamil: 300 nouns, 200 verbs, 100 others. What fraction are nouns?','3/6 = 1/2'),
(34,'Percentage','A novel has 400 pages. Reader finishes 60%. Pages remaining?','160'),
(34,'Ratio','Essay word count: 800 words. Introduction is 1/4. How many words in intro?','200'),
(34,'Series','3, 6, 12, 24, ?','48'),
(34,'Logical','All poets are creative. Some writers are poets. Are all writers creative?','Not necessarily'),
(34,'Time & Work','An editor reviews 50 pages/hour. How long for a 350-page book?','7 hours'),
(41,'Profit & Loss','Tour package costs ₹8000. Sold for ₹9600. Profit percentage?','20%'),
(41,'Percentage','Hotel occupancy: 80 of 100 rooms. Occupancy rate?','80%'),
(41,'Time & Distance','Tourist bus travels 240 km in 4 hours. Speed?','60 km/hr'),
(41,'Ratio','Domestic to international tourists ratio is 7:3. Total 10,000. International tourists?','3000'),
(41,'Data','Revenue Jan-Apr: ₹10L, ₹12L, ₹9L, ₹15L. Average?','₹11.5 lakh'),
(44,'Ratio','Design project: 3 hours concept, 5 hours execution, 2 hours revision. Total 10 hrs. What fraction is execution?','1/2'),
(44,'Percentage','A designer completes 8 of 10 tasks on time. On-time delivery rate?','80%'),
(44,'Series','2, 4, 8, 16, ?','32'),
(44,'Time & Work','Designing a logo takes 4 hours. Working 6 hours/day, how many logos per week (5 days)?','7'),
(44,'Profit & Loss','Freelance project: cost ₹2000 in tools. Charged ₹3500. Profit?','₹1500');

-- ============================================================
-- MOCK INTERVIEW QUESTIONS
-- ============================================================
TRUNCATE TABLE `mock_interview_questions`;
INSERT INTO `mock_interview_questions` (`course_id`, `question`) VALUES
(1,'Walk me through your final year CS project. What problem did it solve?'),
(1,'Explain a data structure you used in a real project and why you chose it.'),
(1,'How would you design a URL shortener system?'),
(1,'Tell me about a bug you found and how you fixed it.'),
(1,'How do you approach learning a new programming language quickly?'),
(2,'Tell me about yourself and one BCA project you are most proud of.'),
(2,'You have to build a simple library management system. Walk me through your approach.'),
(2,'What would you do if you joined a company and found poor coding practices?'),
(2,'Describe a time you worked in a team. What role did you play?'),
(2,'Where do you see yourself in 3 years after this role?'),
(3,'Explain your MCA thesis or major project in 2 minutes.'),
(3,'Design a basic e-commerce checkout system. What components would you include?'),
(3,'How would you handle a performance bottleneck in a web application?'),
(3,'Tell me about a time you had to learn something new quickly on a project.'),
(3,'How do you ensure code quality in a team environment?'),
(6,'Walk me through an end-to-end data analysis project you completed.'),
(6,'A client says their sales are dropping. How would you use data to find the reason?'),
(6,'What is your process when you receive a messy, uncleaned dataset?'),
(6,'How would you explain a complex ML model result to a business team?'),
(6,'Tell me about a time your data findings surprised you.'),
(7,'Tell me about an AI project where your model didn''t perform well initially. What did you do?'),
(7,'How would you approach building a chatbot from scratch?'),
(7,'Explain how you would detect spam emails using machine learning.'),
(7,'What is the most interesting AI paper or development you have read recently?'),
(7,'A model is 99% accurate but failing on minority class. What would you do?'),
(10,'Walk me through a penetration test or security audit you performed or studied.'),
(10,'How would you respond if your company suffered a data breach?'),
(10,'Explain how you would secure a web application from common threats.'),
(10,'Describe a cybersecurity tool you are proficient with and how you used it.'),
(10,'How do you keep up with emerging threats in cybersecurity?'),
(18,'Walk me through how you would prepare a company''s quarterly financial statement.'),
(18,'A client says their expenses are higher than income. How do you help them?'),
(18,'How do you handle a situation where numbers don''t reconcile?'),
(18,'Tell me about a time you found an error in financial data.'),
(18,'Walk me through your understanding of GST filing process.'),
(30,'You are a new team leader. Your team is not meeting deadlines. What do you do?'),
(30,'A major product launch fails in the market. As a manager, how do you respond?'),
(30,'Tell me about a time you had to convince someone who disagreed with your idea.'),
(30,'How would you handle a conflict between two team members?'),
(30,'Describe your biggest leadership challenge so far.'),
(37,'Tell me about yourself in 2 minutes — in Tamil and then in English.'),
(37,'How would you use your Tamil language skills in a content writing role?'),
(37,'Describe a piece of Tamil literature and what you learned from it.'),
(37,'You are applying for a translation role. What is your translation process?'),
(37,'How do you handle working in a multilingual environment?'),
(34,'Tell me about a piece of writing you created that you are proud of.'),
(34,'You need to write a press release in 30 minutes. What is your process?'),
(34,'How do you adapt your writing style for different audiences?'),
(34,'Describe a time your communication skills resolved a conflict.'),
(34,'What digital writing or content tools are you comfortable with?'),
(41,'Design a 5-day South India tour package for a group of 20 seniors.'),
(41,'A guest complains their hotel room is not ready. How do you handle it?'),
(41,'Tell me about yourself and why you chose tourism management.'),
(41,'How would you market a new travel package on social media?'),
(41,'A tour gets disrupted due to bad weather. What is your plan B?'),
(44,'Walk me through your design portfolio in 3 minutes.'),
(44,'A client rejects your design completely. How do you respond?'),
(44,'How do you ensure brand consistency across all design deliverables?'),
(44,'Describe your process for designing a social media campaign from scratch.'),
(44,'What is your approach when you have a creative block?');

-- ============================================================
-- SKILLS
-- ============================================================
TRUNCATE TABLE `skills`;
INSERT INTO `skills` (`course_id`, `skill_name`, `skill_type`) VALUES
(1,'Python','Technical'),(1,'Java','Technical'),(1,'C++','Technical'),
(1,'Data Structures & Algorithms','Technical'),(1,'SQL','Technical'),
(1,'Operating Systems Concepts','Technical'),(1,'Git & GitHub','Technical'),
(1,'Problem Solving','Soft'),(1,'Teamwork','Soft'),(1,'Communication','Soft'),
(2,'Python','Technical'),(2,'Java','Technical'),(2,'HTML & CSS','Technical'),
(2,'SQL','Technical'),(2,'Android Development (basic)','Technical'),
(2,'MS Office','Technical'),(2,'Communication','Soft'),
(2,'Time Management','Soft'),(2,'Teamwork','Soft'),
(3,'Java or Python (advanced)','Technical'),(3,'Spring Boot or Django','Technical'),
(3,'SQL & NoSQL Databases','Technical'),(3,'REST API Development','Technical'),
(3,'Cloud Basics (AWS/Azure)','Technical'),(3,'System Design','Technical'),
(3,'Leadership','Soft'),(3,'Analytical Thinking','Soft'),
(4,'Python','Technical'),(4,'R Programming','Technical'),(4,'Machine Learning','Technical'),
(4,'Research Methodology','Technical'),(4,'LaTeX','Technical'),
(4,'Critical Thinking','Soft'),(4,'Report Writing','Soft'),
(5,'Python','Technical'),(5,'Data Analysis','Technical'),(5,'NLP Basics','Technical'),
(5,'UX Research','Technical'),(5,'Statistical Analysis','Technical'),
(5,'Empathy & Human Understanding','Soft'),(5,'Communication','Soft'),
(6,'Python','Technical'),(6,'Pandas & NumPy','Technical'),(6,'Machine Learning','Technical'),
(6,'SQL','Technical'),(6,'Power BI or Tableau','Technical'),
(6,'Data Storytelling','Soft'),(6,'Problem Solving','Soft'),
(7,'Python or R','Technical'),(7,'TensorFlow or PyTorch','Technical'),
(7,'Deep Learning','Technical'),(7,'Computer Vision Basics','Technical'),
(7,'NLP','Technical'),(7,'Research Skills','Soft'),(7,'Presentation','Soft'),
(8,'Python','Technical'),(8,'Machine Learning','Technical'),(8,'Deep Learning','Technical'),
(8,'Data Visualization','Technical'),(8,'SQL','Technical'),
(8,'Analytical Thinking','Soft'),(8,'Communication','Soft'),
(9,'AWS or Azure or GCP','Technical'),(9,'Linux','Technical'),
(9,'Docker & Kubernetes','Technical'),(9,'Networking Concepts','Technical'),
(9,'Cloud Security','Technical'),(9,'Problem Solving','Soft'),
(10,'Network Security','Technical'),(10,'Penetration Testing','Technical'),
(10,'Kali Linux','Technical'),(10,'Cryptography Basics','Technical'),
(10,'SIEM Tools','Technical'),(10,'Ethical Mindset','Soft'),(10,'Attention to Detail','Soft'),
(11,'MATLAB','Technical'),(11,'Python (NumPy, SciPy)','Technical'),
(11,'R Programming','Technical'),(11,'Statistical Modeling','Technical'),
(11,'LaTeX','Technical'),(11,'Analytical Thinking','Soft'),
(12,'MATLAB','Technical'),(12,'Lab Skills','Technical'),(12,'Data Analysis','Technical'),
(12,'Scientific Writing','Technical'),(12,'Attention to Detail','Soft'),
(13,'Lab Techniques','Technical'),(13,'Chemical Analysis','Technical'),
(13,'MS Excel','Technical'),(13,'Scientific Report Writing','Technical'),
(13,'Safety Protocols','Technical'),(13,'Attention to Detail','Soft'),
(14,'SPSS or R','Technical'),(14,'Research Design','Technical'),
(14,'Counseling Basics','Technical'),(14,'Empathy','Soft'),
(14,'Active Listening','Soft'),(14,'Communication','Soft'),
(15,'Nutritional Assessment','Technical'),(15,'Diet Planning Software','Technical'),
(15,'MS Excel','Technical'),(15,'Patient Communication','Soft'),
(15,'Empathy','Soft'),
(16,'HACCP Principles','Technical'),(16,'Food Safety Standards','Technical'),
(16,'Inventory Management','Technical'),(16,'MS Excel','Technical'),
(16,'Team Leadership','Soft'),(16,'Customer Service','Soft'),
(17,'GIS Tools','Technical'),(17,'Environmental Impact Assessment','Technical'),
(17,'Data Collection & Analysis','Technical'),(17,'Report Writing','Technical'),
(17,'Field Research','Technical'),(17,'Problem Solving','Soft'),
-- Commerce
(18,'Tally ERP','Technical'),(18,'MS Excel','Technical'),(18,'GST Filing','Technical'),
(18,'Financial Statement Analysis','Technical'),(18,'Accounting Principles','Technical'),
(18,'Attention to Detail','Soft'),(18,'Communication','Soft'),
(19,'Company Law','Technical'),(19,'Secretarial Practice','Technical'),
(19,'MS Word & Excel','Technical'),(19,'Board Reporting','Technical'),
(19,'Compliance Management','Technical'),(19,'Integrity','Soft'),(19,'Communication','Soft'),
(20,'Financial Modeling','Technical'),(20,'MS Excel','Technical'),
(20,'Tally ERP','Technical'),(20,'Investment Analysis','Technical'),
(20,'Accounting Standards','Technical'),(20,'Analytical Thinking','Soft'),
(21,'IFRS Knowledge','Technical'),(21,'Advanced Accounting','Technical'),
(21,'MS Excel','Technical'),(21,'Auditing','Technical'),
(21,'Analytical Thinking','Soft'),(21,'Communication','Soft'),
(22,'ERP Systems','Technical'),(22,'Business Intelligence Tools','Technical'),
(22,'MS Excel & Access','Technical'),(22,'Process Documentation','Technical'),
(22,'Analytical Thinking','Soft'),(22,'Teamwork','Soft'),
(23,'Tally ERP','Technical'),(23,'Python for Finance','Technical'),
(23,'SQL','Technical'),(23,'Accounting Software','Technical'),
(23,'Communication','Soft'),(23,'Attention to Detail','Soft'),
(24,'Public Policy Analysis','Technical'),(24,'MS Office','Technical'),
(24,'Report Writing','Technical'),(24,'Government Procedures','Technical'),
(24,'Communication','Soft'),(24,'Leadership','Soft'),
(25,'MIS Tools','Technical'),(25,'ERP Systems','Technical'),
(25,'Database Management','Technical'),(25,'Business Analysis','Technical'),
(25,'Problem Solving','Soft'),(25,'Communication','Soft'),
(26,'Python or R','Technical'),(26,'Blockchain Basics','Technical'),
(26,'Financial Modeling','Technical'),(26,'Data Analysis','Technical'),
(26,'Digital Payments','Technical'),(26,'Analytical Thinking','Soft'),
(27,'International Trade Law Basics','Technical'),(27,'MS Excel','Technical'),
(27,'Cross-Cultural Communication','Soft'),(27,'Foreign Language (basic)','Soft'),
(27,'Negotiation','Soft'),(27,'Analytical Thinking','Soft'),
(28,'Banking Operations','Technical'),(28,'KYC & AML Procedures','Technical'),
(28,'MS Excel','Technical'),(28,'Core Banking Software','Technical'),
(28,'Customer Service','Soft'),(28,'Integrity','Soft'),
(29,'Advanced Financial Analysis','Technical'),(29,'Research Methodology','Technical'),
(29,'MS Excel','Technical'),(29,'Tally ERP','Technical'),
(29,'Analytical Thinking','Soft'),(29,'Communication','Soft'),
(30,'MS Office','Technical'),(30,'CRM Tools','Technical'),
(30,'Project Management Tools','Technical'),(30,'Business Communication','Soft'),
(30,'Leadership','Soft'),(30,'Teamwork','Soft'),(30,'Negotiation','Soft'),
(31,'Google Analytics','Technical'),(31,'SEO Tools (SEMrush/Ahrefs)','Technical'),
(31,'Meta Ads Manager','Technical'),(31,'Canva or Adobe','Technical'),
(31,'Copywriting','Soft'),(31,'Creativity','Soft'),(31,'Data Analysis','Soft'),
(32,'Adobe Illustrator','Technical'),(32,'Photoshop','Technical'),
(32,'Sketching & Pattern Making','Technical'),(32,'Fashion Illustration','Technical'),
(32,'Creativity','Soft'),(32,'Attention to Detail','Soft'),
(33,'Airport Operations Knowledge','Technical'),(33,'MS Office','Technical'),
(33,'Safety & Security Protocols','Technical'),(33,'Aviation Terminology','Technical'),
(33,'Customer Service','Soft'),(33,'Stress Management','Soft'),
-- Arts
(34,'Content Writing','Technical'),(34,'MS Word','Technical'),
(34,'Research Skills','Technical'),(34,'SEO Basics','Technical'),
(34,'Communication','Soft'),(34,'Creativity','Soft'),(34,'Critical Thinking','Soft'),
(35,'Historical Research','Technical'),(35,'MS Office','Technical'),
(35,'Archival Research Skills','Technical'),(35,'Report Writing','Technical'),
(35,'Analytical Thinking','Soft'),(35,'Communication','Soft'),
(36,'Statistical Analysis','Technical'),(36,'MS Excel','Technical'),
(36,'Economic Research','Technical'),(36,'Report Writing','Technical'),
(36,'Analytical Thinking','Soft'),(36,'Communication','Soft'),
(37,'Tamil Communication','Technical'),(37,'Content Writing in Tamil','Technical'),
(37,'Translation','Technical'),(37,'MS Word','Technical'),
(37,'Communication','Soft'),(37,'Creativity','Soft'),
(38,'Hindi Communication','Technical'),(38,'Translation','Technical'),
(38,'Content Writing','Technical'),(38,'MS Word','Technical'),
(38,'Communication','Soft'),(38,'Creativity','Soft'),
(39,'Sanskrit Scholarship','Technical'),(39,'Research Skills','Technical'),
(39,'Manuscript Analysis','Technical'),(39,'Communication','Soft'),
(40,'French Language Proficiency','Technical'),(40,'Translation','Technical'),
(40,'Content Writing','Technical'),(40,'Cross-Cultural Communication','Soft'),
(41,'Tour Planning','Technical'),(41,'GDS Software Basics','Technical'),
(41,'MS Office','Technical'),(41,'Customer Service','Soft'),
(41,'Communication','Soft'),(41,'Problem Solving','Soft'),
(42,'Advanced Content Writing','Technical'),(42,'Research Methodology','Technical'),
(42,'Critical Thinking','Soft'),(42,'Communication','Soft'),
(43,'Tamil Literature Expertise','Technical'),(43,'Research Skills','Technical'),
(43,'Tamil Content Writing','Technical'),(43,'Communication','Soft'),
(44,'Adobe Photoshop','Technical'),(44,'Illustrator','Technical'),
(44,'Premiere Pro','Technical'),(44,'Canva','Technical'),
(44,'UI/UX Basics','Technical'),(44,'Creativity','Soft'),(44,'Attention to Detail','Soft'),
(45,'Research Design','Technical'),(45,'SPSS or Excel','Technical'),
(45,'Field Research','Technical'),(45,'Report Writing','Technical'),
(45,'Empathy','Soft'),(45,'Communication','Soft');

-- ============================================================
-- CODING PROBLEMS (NEW TABLE)
-- ============================================================
TRUNCATE TABLE `coding_problems`;
INSERT INTO `coding_problems` (`course_id`, `problem`, `difficulty`, `hint`) VALUES
-- CS (1)
(1,'Reverse a string without using built-in reverse functions.','Easy','Use a loop from end to start'),
(1,'Find all pairs in an array that sum to a target value.','Medium','Use a hash set for O(n) time'),
(1,'Implement a binary search algorithm.','Easy','Divide and conquer — compare mid element'),
(1,'Check if a linked list has a cycle.','Medium','Use slow and fast pointer technique'),
(1,'Write SQL to find the second highest salary.','Easy','Use LIMIT with OFFSET or subquery'),
-- BCA (2)
(2,'Print all prime numbers up to N.','Easy','Check divisibility up to sqrt(N)'),
(2,'Find the factorial of a number using recursion.','Easy','Base case: factorial(0) = 1'),
(2,'Check if a string is a palindrome.','Easy','Compare characters from both ends'),
(2,'Write a program to sort an array using bubble sort.','Easy','Nested loop, swap adjacent elements'),
(2,'Count occurrences of each character in a string.','Easy','Use a dictionary or hashmap'),
-- MCA (3)
(3,'Implement a stack using an array.','Easy','Push to end, pop from end'),
(3,'Design a simple REST API endpoint structure for a student system.','Medium','Consider GET, POST, PUT, DELETE'),
(3,'Write a SQL query to find departments with more than 5 employees.','Easy','GROUP BY with HAVING COUNT'),
(3,'Implement merge sort on an array.','Medium','Divide in halves, sort and merge'),
(3,'Find the longest common substring between two strings.','Hard','Use dynamic programming'),
-- DS (6)
(6,'Write Python code to read a CSV and display the first 5 rows.','Easy','Use pandas read_csv and head()'),
(6,'Calculate mean, median, mode of a list.','Easy','Use statistics module or numpy'),
(6,'Plot a bar chart of monthly sales using matplotlib.','Easy','Use plt.bar() with labels'),
(6,'Handle missing values in a dataset — fill with mean.','Easy','df.fillna(df.mean())'),
(6,'Split a dataset into 80% train and 20% test.','Easy','Use sklearn train_test_split'),
-- AI (7)
(7,'Write code to create a simple linear regression model using sklearn.','Medium','Use LinearRegression().fit()'),
(7,'Implement a K-Nearest Neighbors classifier.','Medium','Use sklearn KNeighborsClassifier'),
(7,'Write a confusion matrix evaluation for a classification model.','Easy','Use sklearn confusion_matrix'),
(7,'Tokenize a sentence using NLTK.','Easy','Use nltk.word_tokenize()'),
(7,'Train a decision tree on the Iris dataset.','Easy','Use sklearn DecisionTreeClassifier'),
-- CLOUD (9)
(9,'Write a simple AWS Lambda function to return hello world.','Easy','Use Python handler function'),
(9,'Create a Docker file for a Python Flask application.','Medium','FROM python:3.9, COPY, RUN pip install'),
(9,'Write a basic Kubernetes deployment YAML.','Medium','Include apiVersion, kind, metadata'),
(9,'Write a bash script to monitor server CPU usage.','Easy','Use top command and grep'),
(9,'Describe how you would set up auto-scaling for a web app.','Medium','Consider load balancer and scaling policies'),
-- CYBER (10)
(10,'Write a Python script to scan open ports on a localhost.','Medium','Use socket module with try-except'),
(10,'Implement a basic Caesar cipher in Python.','Easy','Shift each character by key value'),
(10,'Write code to hash a password using SHA-256.','Easy','Use hashlib.sha256()'),
(10,'Simulate a basic SQL injection and show parameterized query fix.','Medium','Use ? placeholders in queries'),
(10,'Write a Python script to read and parse a web server access log.','Medium','Open file, split lines, extract IP'),
-- Commerce
(18,'Write Excel formula to calculate compound interest for 5 years.','Easy','=P*(1+r)^n'),
(18,'Write SQL to find total revenue by product category.','Easy','SELECT category, SUM(revenue) GROUP BY category'),
(18,'Create a Python script to calculate GST (18%) on a list of prices.','Easy','price * 0.18'),
(18,'Find duplicate entries in an Excel column — what formula to use?','Easy','Use COUNTIF > 1'),
(18,'Write SQL to find customers who have not placed any order.','Medium','LEFT JOIN with WHERE NULL'),
(30,'Write Python to automate sending email reminders.','Medium','Use smtplib module'),
(30,'Build a simple employee attendance tracker in Excel with formulas.','Easy','Use COUNTIF for present/absent'),
(30,'Write SQL to find top 5 best-selling products.','Easy','ORDER BY sales DESC LIMIT 5'),
(30,'Create a basic financial dashboard in Excel.','Medium','Use charts, SUMIF, pivot tables'),
(30,'Write a Python script to read monthly expenses from CSV and find highest.','Easy','Use pandas max()'),
(31,'Write Python to count hashtag occurrences from a list of social posts.','Easy','Use Counter from collections'),
(31,'Build a simple keyword density counter for SEO.','Easy','Split text, count word frequency'),
(31,'Write SQL to find which campaign got the most clicks.','Easy','ORDER BY clicks DESC LIMIT 1'),
(31,'Write Python to schedule a social media post (simulated).','Medium','Use datetime and time.sleep'),
(31,'Create a bar chart of website traffic by month using matplotlib.','Easy','plt.bar(months, traffic)'),
-- Arts
(37,'Write Python to translate English words to Tamil using a dictionary.','Easy','Use a Python dict mapping'),
(37,'Count words in a Tamil paragraph using Python.','Easy','Use split() and len()'),
(37,'Write Python to find the longest word in a Tamil text.','Easy','Use max() with key=len'),
(37,'Create a simple word frequency counter for a text file.','Easy','Use Counter from collections'),
(37,'Write Python to check if a word is a palindrome.','Easy','word == word[::-1]'),
(34,'Write Python to count words in an essay.','Easy','len(text.split())'),
(34,'Build a simple spell checker list in Python.','Easy','Compare against a word list'),
(34,'Write a basic HTML page for a writer''s portfolio.','Easy','Use HTML tags: h1, p, img, a'),
(34,'Write Python to extract emails from a text string.','Easy','Use re.findall with email pattern'),
(34,'Create a content calendar template in Excel.','Easy','Use date columns and content columns'),
(41,'Write Python to calculate total tour cost from a list of expenses.','Easy','Use sum()'),
(41,'Build a simple itinerary planner in Excel with days and activities.','Easy','Use table with date, place, activity'),
(41,'Write SQL to find most booked tour destinations.','Easy','GROUP BY destination ORDER BY COUNT DESC'),
(41,'Write Python to generate a booking confirmation message.','Easy','Use f-strings for formatted output'),
(41,'Create a customer feedback form in HTML.','Easy','Use form, input, textarea tags'),
(44,'Write HTML and CSS for a basic design portfolio page.','Easy','Use flexbox for layout'),
(44,'Write Python to resize a batch of images using Pillow.','Medium','Use PIL Image.open().resize()'),
(44,'Create an SVG logo template using basic shapes.','Easy','Use rect, circle, text in SVG'),
(44,'Write JavaScript to create a simple image slideshow.','Medium','Use setInterval and DOM manipulation'),
(44,'Build a color palette generator in Python.','Easy','Use random to generate RGB values');

-- ============================================================
-- CODING TOPICS (General fallback)
-- ============================================================
TRUNCATE TABLE `coding_topics`;
INSERT INTO `coding_topics` (`topic`, `description`) VALUES
('Arrays & Strings','Core data structure — sorting, searching, two-pointer problems'),
('Linked Lists','Singly, doubly linked lists — insert, delete, reverse operations'),
('Stacks & Queues','LIFO and FIFO structures — bracket matching, BFS applications'),
('Trees & Graphs','Binary trees, BST, DFS, BFS, shortest path algorithms'),
('Dynamic Programming','Memoization, tabulation — 0/1 knapsack, longest common subsequence'),
('Sorting Algorithms','Bubble, merge, quick, heap sort — time complexity comparison'),
('SQL Queries','SELECT, JOIN, GROUP BY, HAVING, subqueries, indexes'),
('Object-Oriented Programming','Classes, inheritance, polymorphism, encapsulation examples'),
('Recursion','Base case design, tree traversal, factorial, Fibonacci'),
('System Design Basics','Load balancing, caching, database sharding, API design');

-- ============================================================
-- ATS KEYWORDS
-- ============================================================
TRUNCATE TABLE `ats_keywords`;
INSERT INTO `ats_keywords` (`course_id`, `keyword`) VALUES
-- CS (1)
(1,'python'),(1,'java'),(1,'c++'),(1,'data structures'),(1,'algorithms'),
(1,'sql'),(1,'os'),(1,'networking'),(1,'git'),(1,'problem solving'),
(1,'object oriented programming'),(1,'dbms'),(1,'linux'),(1,'html'),(1,'css'),
-- BCA (2)
(2,'python'),(2,'java'),(2,'html'),(2,'css'),(2,'sql'),(2,'android'),
(2,'ms office'),(2,'communication'),(2,'teamwork'),(2,'dbms'),
(2,'object oriented programming'),(2,'git'),(2,'javascript'),
-- MCA (3)
(3,'java'),(3,'python'),(3,'spring boot'),(3,'rest api'),(3,'sql'),(3,'nosql'),
(3,'system design'),(3,'cloud'),(3,'docker'),(3,'microservices'),
(3,'git'),(3,'agile'),(3,'data structures'),
-- DS (6)
(6,'python'),(6,'pandas'),(6,'numpy'),(6,'machine learning'),(6,'sql'),
(6,'power bi'),(6,'tableau'),(6,'data visualization'),(6,'statistics'),
(6,'feature engineering'),(6,'scikit-learn'),(6,'matplotlib'),(6,'data analysis'),
-- AI (7)
(7,'python'),(7,'tensorflow'),(7,'pytorch'),(7,'deep learning'),(7,'machine learning'),
(7,'nlp'),(7,'computer vision'),(7,'neural networks'),(7,'scikit-learn'),
(7,'data analysis'),(7,'statistics'),(7,'research'),
-- CLOUD (9)
(9,'aws'),(9,'azure'),(9,'gcp'),(9,'docker'),(9,'kubernetes'),(9,'linux'),
(9,'terraform'),(9,'networking'),(9,'cloud security'),(9,'python'),
(9,'bash scripting'),(9,'ci/cd'),
-- CYBER (10)
(10,'network security'),(10,'penetration testing'),(10,'kali linux'),(10,'python'),
(10,'ethical hacking'),(10,'cryptography'),(10,'firewalls'),(10,'siem'),
(10,'vulnerability assessment'),(10,'incident response'),
-- MATHS (11)
(11,'matlab'),(11,'python'),(11,'r'),(11,'statistics'),(11,'linear algebra'),
(11,'data analysis'),(11,'research'),(11,'latex'),(11,'problem solving'),
-- BCOM (18)
(18,'tally'),(18,'ms excel'),(18,'gst'),(18,'accounting'),(18,'financial statements'),
(18,'taxation'),(18,'bookkeeping'),(18,'communication'),(18,'analytical thinking'),
(18,'bank reconciliation'),(18,'audit'),
-- BBA (30)
(30,'ms office'),(30,'communication'),(30,'leadership'),(30,'teamwork'),
(30,'marketing'),(30,'crm'),(30,'project management'),(30,'presentation'),
(30,'problem solving'),(30,'customer service'),
-- FINTECH (26)
(26,'python'),(26,'blockchain'),(26,'sql'),(26,'financial modeling'),(26,'excel'),
(26,'digital payments'),(26,'data analysis'),(26,'machine learning'),(26,'upi'),
-- DM (31)
(31,'seo'),(31,'google analytics'),(31,'meta ads'),(31,'content writing'),
(31,'social media marketing'),(31,'email marketing'),(31,'canva'),
(31,'copywriting'),(31,'data analysis'),(31,'crm'),
-- TAMIL (37)
(37,'tamil'),(37,'communication'),(37,'content writing'),(37,'translation'),
(37,'ms word'),(37,'research'),(37,'presentation'),(37,'leadership'),
(37,'teamwork'),(37,'analytical thinking'),
-- ENG (34)
(34,'content writing'),(34,'communication'),(34,'ms word'),(34,'research'),
(34,'editing'),(34,'proofreading'),(34,'seo writing'),(34,'presentation'),
(34,'creative writing'),(34,'analytical thinking'),
-- TOURISM (41)
(41,'tour planning'),(41,'customer service'),(41,'ms office'),(41,'communication'),
(41,'gds software'),(41,'itinerary planning'),(41,'leadership'),(41,'teamwork'),
(41,'problem solving'),(41,'multilingual'),
-- VISCOM (44)
(44,'adobe photoshop'),(44,'illustrator'),(44,'premiere pro'),(44,'canva'),
(44,'ui design'),(44,'ux research'),(44,'typography'),(44,'branding'),
(44,'photography'),(44,'video editing'),
-- HISTORY (35)
(35,'research'),(35,'ms office'),(35,'report writing'),(35,'communication'),
(35,'analytical thinking'),(35,'documentation'),(35,'presentation'),
-- ECO (36)
(36,'ms excel'),(36,'statistical analysis'),(36,'research'),(36,'communication'),
(36,'report writing'),(36,'data analysis'),(36,'presentation'),
-- COGNITIVE (5)
(5,'python'),(5,'data analysis'),(5,'nlp'),(5,'ux research'),(5,'statistics'),
(5,'communication'),(5,'research'),
-- PSY (14)
(14,'spss'),(14,'research design'),(14,'communication'),(14,'empathy'),
(14,'counseling'),(14,'data analysis'),(14,'report writing'),
-- CND (15)
(15,'diet planning'),(15,'nutrition assessment'),(15,'ms excel'),(15,'communication'),
(15,'patient counseling'),(15,'research'),
-- AIRPORT (33)
(33,'customer service'),(33,'ms office'),(33,'aviation regulations'),
(33,'communication'),(33,'operations management'),(33,'safety protocols');

-- ============================================================
-- COMPANIES
-- ============================================================
TRUNCATE TABLE `companies`;
INSERT INTO `companies` (`company_name`, `role`, `salary`, `type`, `stream`) VALUES
-- Science
('TCS','Software Developer','₹3.5 LPA','On-Campus','science'),
('Infosys','Systems Engineer','₹3.6 LPA','On-Campus','science'),
('Wipro','Project Engineer','₹3.5 LPA','On-Campus','science'),
('Cognizant','Programmer Analyst','₹4 LPA','On-Campus','science'),
('Zoho','Software Developer','₹6–8 LPA','Referral','science'),
('HCL Technologies','Graduate Engineer Trainee','₹3.5 LPA','On-Campus','science'),
('Accenture','Associate Software Engineer','₹4.5 LPA','On-Campus','science'),
('Capgemini','Analyst','₹3.8 LPA','On-Campus','science'),
('Tech Mahindra','Graduate Trainee','₹3.5 LPA','On-Campus','science'),
('Amazon','Operations Trainee','₹4 LPA','Off-Campus','science'),
('IBM','Associate Developer','₹4.2 LPA','On-Campus','science'),
('Freshworks','Junior Developer','₹7 LPA','Off-Campus','science'),
-- Commerce
('Deloitte','Business Analyst','₹5 LPA','On-Campus','commerce'),
('HDFC Bank','Banking Associate','₹3–4 LPA','On-Campus','commerce'),
('ICICI Bank','Relationship Manager','₹3.5 LPA','On-Campus','commerce'),
('Axis Bank','Banking Executive','₹3 LPA','On-Campus','commerce'),
('KPMG','Audit Associate','₹5 LPA','On-Campus','commerce'),
('EY (Ernst & Young)','Associate','₹4.5 LPA','On-Campus','commerce'),
('PwC','Junior Associate','₹4 LPA','On-Campus','commerce'),
('Infosys BPO','Process Executive','₹2.5 LPA','On-Campus','commerce'),
('Wipro BPS','Business Process Associate','₹2.5 LPA','On-Campus','commerce'),
('Bajaj Finserv','Sales Executive','₹3 LPA','On-Campus','commerce'),
('Gartner','Research Associate','₹4 LPA','Off-Campus','commerce'),
('Amazon','Finance Operations','₹4.5 LPA','Off-Campus','commerce'),
-- Arts
('Concentrix','Customer Support Executive','₹2.5 LPA','On-Campus','arts'),
('Sutherland','Process Associate','₹2.5 LPA','On-Campus','arts'),
('EY','Content & Communications','₹3.5 LPA','Off-Campus','arts'),
('Cognizant BPS','Customer Service','₹3 LPA','On-Campus','arts'),
('HCL BPO','Support Executive','₹2.5 LPA','On-Campus','arts'),
('Times of India Group','Content Writer / Trainee','₹2.5 LPA','Off-Campus','arts'),
('iEnergizer','Customer Service Rep','₹2.5 LPA','On-Campus','arts'),
('Firstsource','Associate','₹2.5 LPA','On-Campus','arts'),
('Mphasis BPO','Customer Support','₹3 LPA','On-Campus','arts'),
('MakeMyTrip','Travel Consultant','₹3 LPA','Off-Campus','arts'),
('Thomas Cook','Tour Executive','₹2.5 LPA','Off-Campus','arts');

-- ============================================================
-- RESUME TIPS
-- ============================================================
TRUNCATE TABLE `resume_tips`;
INSERT INTO `resume_tips` (`tip`) VALUES
('Keep your resume to 1 page for freshers.'),
('Use a clean, ATS-friendly font like Arial or Calibri, size 11–12.'),
('Start bullet points with strong action verbs: Developed, Designed, Analyzed, Built.'),
('Quantify achievements wherever possible — numbers stand out to recruiters.'),
('Tailor your resume for each job by matching keywords from the job description.'),
('Avoid photos, tables, graphics, and columns — they confuse ATS scanners.'),
('List skills that match the job — do not add irrelevant hobbies.'),
('Include a short professional objective/summary at the top.'),
('Save your resume as PDF (or DOCX if specified) — never send .pages or .txt.'),
('Proofread carefully — spelling errors can instantly disqualify you.'),
('Include your GitHub, LinkedIn, or portfolio link if relevant.'),
('Use consistent formatting — same font, size, and spacing throughout.');

SET FOREIGN_KEY_CHECKS = 1;
-- END OF DATASET
